### ISSUE TITLE
Server error in recent logs

### ISSUE THREAD

**Issue by Lineflyer** [cgeo/cgeo-status#13]
Don't know if this is relevant or a temporary disturbance.
Just today I tested with a RC currently under deployment (will probably never be released) and have seen this in the log:
```
22:48:10.214 Debug cgeo 12118  [OkHttp] GET https://status.cgeo.org/api/status.json?version_code=20170211&version_name=2017.02.12-RC&locale=de_DE
22:48:10.761 Debug cgeo 12118  [OkHttp] 500 [Internal Server Error] (562 ms) GET https://status.cgeo.org/api/status.json?version_code=20170211&version_name=2017.02.12-RC&locale=de_DE (http/1.1)
```

**Comment by samueltardieu** [comment]
Log on the server side:

```
2017-02-20T21:59:18.469050+00:00 app[web.1]: [error] application - 
2017-02-20T21:59:18.469064+00:00 app[web.1]: 
2017-02-20T21:59:18.469065+00:00 app[web.1]: ! @735gi9gh3 - Internal server error, for (GET) [/api/status.json?version_code=20170211&version_name=2017.02.12-RC&locale=de_DE] ->
2017-02-20T21:59:18.469065+00:00 app[web.1]:  
2017-02-20T21:59:18.469066+00:00 app[web.1]: play.api.UnexpectedException: Unexpected exception[MatchError: models.ReleaseCandidateDeployment$@65303dab (of class models.ReleaseCandidateDeployment$)]
2017-02-20T21:59:18.469067+00:00 app[web.1]: 	at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:289)
2017-02-20T21:59:18.469068+00:00 app[web.1]: 	at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:220)
2017-02-20T21:59:18.469069+00:00 app[web.1]: 	at play.api.GlobalSettings$class.onError(GlobalSettings.scala:160)
2017-02-20T21:59:18.469069+00:00 app[web.1]: 	at play.api.DefaultGlobal$.onError(GlobalSettings.scala:188)
2017-02-20T21:59:18.469070+00:00 app[web.1]: 	at play.api.http.GlobalSettingsHttpErrorHandler.onServerError(HttpErrorHandler.scala:100)
2017-02-20T21:59:18.469071+00:00 app[web.1]: 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:100)
2017-02-20T21:59:18.469071+00:00 app[web.1]: 	at play.core.server.netty.PlayRequestHandler$$anonfun$2$$anonfun$apply$1.applyOrElse(PlayRequestHandler.scala:99)
2017-02-20T21:59:18.469071+00:00 app[web.1]: 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:346)
2017-02-20T21:59:18.469072+00:00 app[web.1]: 	at scala.concurrent.Future$$anonfun$recoverWith$1.apply(Future.scala:345)
2017-02-20T21:59:18.469072+00:00 app[web.1]: 	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:32)
2017-02-20T21:59:18.469073+00:00 app[web.1]: Caused by: scala.MatchError: models.ReleaseCandidateDeployment$@65303dab (of class models.ReleaseCandidateDeployment$)
2017-02-20T21:59:18.469073+00:00 app[web.1]: 	at models.Status.status(Status.scala:64)
2017-02-20T21:59:18.469074+00:00 app[web.1]: 	at controllers.API$$anonfun$getStatus$1.apply(API.scala:34)
2017-02-20T21:59:18.469074+00:00 app[web.1]: 	at controllers.API$$anonfun$getStatus$1.apply(API.scala:33)
2017-02-20T21:59:18.469075+00:00 app[web.1]: 	at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:371)
2017-02-20T21:59:18.469075+00:00 app[web.1]: 	at play.api.mvc.ActionBuilder$$anonfun$apply$13.apply(Action.scala:370)
2017-02-20T21:59:18.469075+00:00 app[web.1]: 	at play.api.mvc.Action$.invokeBlock(Action.scala:498)
2017-02-20T21:59:18.469076+00:00 app[web.1]: 	at play.api.mvc.Action$.invokeBlock(Action.scala:495)
2017-02-20T21:59:18.469076+00:00 app[web.1]: 	at play.api.mvc.ActionBuilder$$anon$2.apply(Action.scala:458)
2017-02-20T21:59:18.469077+00:00 app[web.1]: 	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
2017-02-20T21:59:18.469077+00:00 app[web.1]: 	at play.api.mvc.Action$$anonfun$apply$2$$anonfun$apply$5$$anonfun$apply$6.apply(Action.scala:112)
```
